# -*- coding: utf-8 -*-
"""Econ441B-PlotADataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uOfUtj7to91OgyjKzsHEowe6vNzEScTz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive

"""Step 1: Set Filepath"""

drive.mount('/content/gdrive/', force_remount=True)

"""Step 2: read csv"""

df = pd.read_csv("/content/gdrive/MyDrive/Econ441B/GDP.csv")

"""Step 3: Set Index to Datetime"""

df["DATE"] = pd.to_datetime(df.DATE)

df = df.set_index("DATE")

"""Step 4: Plot"""

plt.figure(figsize = (10, 5))
plt.plot(df)
plt.title("GDP")
plt.xlabel("DATE")
plt.ylabel("INDEX")
plt.grid()
plt.show()

"""Comment: GDP increase continuously"""