# -*- coding: utf-8 -*-
"""Econ441B-Week2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oy5CcY-CHNPdpNMwHxZr2BnO1jOpkQbB

# **Import the data from CCLE into a new Google Colab file**

Name: Jie Hou

Uid: 005643341
"""

import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt

drive.mount('/content/gdrive/', force_remount = True)

df = pd.read_csv("/content/gdrive/MyDrive/Econ441B/insurance.csv")

df.loc[df["sex"] == "female","sex"] = 1.
df.loc[df["sex"] == "male","sex"] = 0.

### CONVERT smoker and region.
# smoker
df.loc[df['smoker'] == 'yes', 'smoker'] = 1 
df.loc[df['smoker'] == 'no', 'smoker'] = 0

# region
df = df.merge(pd.get_dummies(df.region), left_index = True, right_index = True)

df.head()

"""# **Split the data into 80/20, in/out sample**"""

import numpy as np

col = ["age", "sex", "bmi", "children", "smoker", "northeast", "northwest", "southeast"]
sub = df[col]
data = np.array(sub)
target = np.array(df.loc[:, "charges"])

display(data)

display(target)

cut = int((len(data) * .8) // 1)

in_data = data[:cut]
out_data = data[cut:]

in_target = target[:cut]
out_target = target[cut:]

"""# **Normalize the Data**"""

from sklearn import preprocessing

scaler = preprocessing.StandardScaler().fit(in_data)
in_data_scale = scaler.transform(in_data)

out_data_scale = scaler.transform(out_data)

"""# **Get lambda from Lasso cross validation**"""

from sklearn.linear_model import LassoCV

modCV = LassoCV().fit(in_data_scale, in_target)

# Optimized Lambda
a = modCV.alpha_ 
display(a)

"""# **Run a lasso regression with that Lambda**"""

from sklearn.linear_model import Lasso
model = Lasso(alpha = a).fit(in_data_scale, in_target)
in_y_pred = model.predict(in_data_scale)
out_y_pred = model.predict(out_data_scale)

model.coef_

"""# **Visualize the coefficients**"""

plt.figure(figsize = (10, 6))
plt.bar(col, model.coef_)
plt.xlabel("Parameters")
plt.ylabel("Coefficient")
plt.show()

"""# **Interpret the coefficients**

From the plot, we can conclude that \
**1.** Age has significant influence on buying health insurance.\
**2.** Sex has no influence on buying health insurance.\
**3.** Bmi has significant influence on buying health insurance.\
**4.** The family with children intend to spend more on health insurance.\
**5.** Smoke habit has strong influence on spending health insurance.\
**6.** People live in northeast has more desire to buy health insurance compare to that in the southwest.

# **Compare in and out of sample MSE’s**
"""

from sklearn.metrics import mean_squared_error
out_sample_mse = mean_squared_error(out_y_pred, out_target)
in_sampe_mse = mean_squared_error(in_y_pred, in_target)

display(in_sampe_mse, out_sample_mse)

plt.bar(["in", "out"], [in_sampe_mse, out_sample_mse])
plt.xlabel("MSE")
plt.ylabel("Value")
plt.show()
